#!/bin/bash

# # INSTALLATION
# 🚨 install from main (bugfixes not in release yet?)
# brew uninstall borders (to update)
# brew install borders --head

# # USAGE
# https://github.com/FelixKratz/JankyBorders
# brew services start borders
# brew services stop borders
# brew services restart borders

# 🚨 reload dotfiles when options change
options=(
  style=round
  # style=square
  width=12.0
  hidpi=on
  # active_color=0xFF238636
  # active_color=0xFFBBBBBB
  # active_color=0xFFCCC8AE # yellowish

  active_color=0x666C6062 # dark shadowish
  # active_color=0xFFaeffae # greenish

  # white=0xffe2e2e3
  # purple=0xFFD2A5FC
  # blue=0xFF1FCDFF
  # red=0xFFF78166
  # green=0xFF238636
  # golden=0xFF238636
  # yellow=0xFFFFD700
  # active_color=0xFFD2A5FC
  # active_color=gradient(top_left=0xFFD2A5FC,bottom_right=0xFF238636)
  # inactive_color=0xc02c2e34
  # background_color=0x302c2e34
)

borders "${options[@]}"
