# Setup:
# 1. Run `kitten quick-access-terminal`
# 2. System Preferences->Keyboard->Keyboard Shortcuts->Services->General and set a shortcut for the Quick access to kitty entry.

kitty_override startup_session ~/.config/kitty/sessions/tmux.kitty-session

background_opacity 1
# background_blur 0

# edge right
# margin_top 6

# edge center
# margin_right 200
# margin_left 200
# margin_top 100
# margin_bottom 100

edge center-sized
# fits mbp
# lines 900px
# columns 1200px

# big display
lines 1800px
columns 2000px

# margin_left 600
# margin_right 600

# edge center-sized
# columns 1600 px
# lines 2000 px
