[general]
live_config_reload = true
import = ["~/.config/alacritty/tokyonight_night.toml"]

[window]
decorations = "buttonless"
opacity = 0.9
blur = true
dynamic_title = true
padding.x = 10
padding.y = 10

[colors.primary]
background = '#0F0F19'

[font]
size = 16.0
normal = { family = "SFMono Nerd Font" }
offset.y =  16
glyph_offset.y = 8

[keyboard]
bindings = [
  { key = "Enter", mods = "Control | Shift", action = "ToggleFullScreen" },
  { key = "N", mods = "Control | Shift", action = "CreateNewWindow" },
]
